config/routes.rb
Rails.application.routes.draw do

  
  
  resources :perfils
  resources :religiaos
  resources :enderecos
  resources :paroquias
  resources :filhos
  resources :profissaos
  resources :casamentos
  resources :membros
  devise_for :usuarios 
  root  to: 'casamentos#index'
  

end

app/models/casamento.rb
class Casamento < ActiveRecord::Base
end

app/models/endereco.rb
class Endereco < ActiveRecord::Base
end

app/models/filho.rb
class Filho < ActiveRecord::Base
    belongs_to :casamento
end

app/models/membro.rb
class Membro < ActiveRecord::Base
    belongs_to :profissao
    belongs_to :paroquia
    belongs_to :usuario
    belongs_to :casamento
    belongs_to :religiao
    belongs_to :endereco
    belongs_to :endereco_profissional, class_name: 'Endereco', foreign_key: :endereco_profissao_id    
end

app/models/paroquia.rb
class Paroquia < ActiveRecord::Base
    self.table_name = :paroquias
    belongs_to :endereco
end

app/models/perfil.rb
class Perfil < ActiveRecord::Base
end

app/models/profissao.rb
class Profissao < ActiveRecord::Base
end

app/models/religiao.rb
class Religiao < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :esposo, class_name: 'Membro', foreign_key: :usuario_id
  has_one :esposa, class_name: 'Membro', foreign_key: :usuario_id

  

  accepts_nested_attributes_for :esposo
  accepts_nested_attributes_for :esposa
  belongs_to :perfil
end

app/controllers/casamentos_controller.rb
class CasamentosController < GeccController
  before_action :set_casamento, only: [:show, :edit, :update, :destroy]

  # GET /casamentos
  # GET /casamentos.json
  def index
    @casamentos = Casamento.all
  end

  # GET /casamentos/1
  # GET /casamentos/1.json
  def show
  end

  # GET /casamentos/new
  def new
    @casamento = Casamento.new
  end

  # GET /casamentos/1/edit
  def edit
  end

  # POST /casamentos
  # POST /casamentos.json
  def create
    @casamento = Casamento.new(casamento_params)

    respond_to do |format|
      if @casamento.save
        format.html { redirect_to @casamento, notice: 'Casamento was successfully created.' }
        format.json { render :show, status: :created, location: @casamento }
      else
        format.html { render :new }
        format.json { render json: @casamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /casamentos/1
  # PATCH/PUT /casamentos/1.json
  def update
    respond_to do |format|
      if @casamento.update(casamento_params)
        format.html { redirect_to @casamento, notice: 'Casamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @casamento }
      else
        format.html { render :edit }
        format.json { render json: @casamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /casamentos/1
  # DELETE /casamentos/1.json
  def destroy
    @casamento.destroy
    respond_to do |format|
      format.html { redirect_to casamentos_url, notice: 'Casamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_casamento
      @casamento = Casamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def casamento_params
      params.require(:casamento).permit(:paroquia_id, :esposo, :esposa, :data, :religioso, :civil, :separados)
    end
end

app/controllers/filhos_controller.rb
class FilhosController < GeccController
  before_action :set_filho, only: [:show, :edit, :update, :destroy]

  # GET /filhos
  # GET /filhos.json
  def index
    @filhos = Filho.all
  end

  # GET /filhos/1
  # GET /filhos/1.json
  def show
  end

  # GET /filhos/new
  def new
    @filho = Filho.new
  end

  # GET /filhos/1/edit
  def edit
  end

  # POST /filhos
  # POST /filhos.json
  def create
    @filho = Filho.new(filho_params)

    respond_to do |format|
      if @filho.save
        format.html { redirect_to @filho, notice: 'Filho was successfully created.' }
        format.json { render :show, status: :created, location: @filho }
      else
        format.html { render :new }
        format.json { render json: @filho.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /filhos/1
  # PATCH/PUT /filhos/1.json
  def update
    respond_to do |format|
      if @filho.update(filho_params)
        format.html { redirect_to @filho, notice: 'Filho was successfully updated.' }
        format.json { render :show, status: :ok, location: @filho }
      else
        format.html { render :edit }
        format.json { render json: @filho.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filhos/1
  # DELETE /filhos/1.json
  def destroy
    @filho.destroy
    respond_to do |format|
      format.html { redirect_to filhos_url, notice: 'Filho was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_filho
      @filho = Filho.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def filho_params
      params.require(:filho).permit(:casamento_id, :nome, :data_nascimento)
    end
end

app/controllers/gecc_controller.rb
class GeccController < ApplicationController
    before_action :authenticate_user!
end

app/controllers/membros_controller.rb
class MembrosController < GeccController
  before_action :set_membro, only: [:show, :edit, :update, :destroy]

  # GET /membros
  # GET /membros.json
  def index
    @membros = Membro.all
  end

  # GET /membros/1
  # GET /membros/1.json
  def show
  end

  # GET /membros/new
  def new
    @membro = Membro.new
  end

  # GET /membros/1/edit
  def edit
  end

  # POST /membros
  # POST /membros.json
  def create
    @membro = Membro.new(membro_params)

    respond_to do |format|
      if @membro.save
        format.html { redirect_to @membro, notice: 'Membro was successfully created.' }
        format.json { render :show, status: :created, location: @membro }
      else
        format.html { render :new }
        format.json { render json: @membro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /membros/1
  # PATCH/PUT /membros/1.json
  def update
    respond_to do |format|
      if @membro.update(membro_params)
        format.html { redirect_to @membro, notice: 'Membro was successfully updated.' }
        format.json { render :show, status: :ok, location: @membro }
      else
        format.html { render :edit }
        format.json { render json: @membro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /membros/1
  # DELETE /membros/1.json
  def destroy
    @membro.destroy
    respond_to do |format|
      format.html { redirect_to membros_url, notice: 'Membro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membro
      @membro = Membro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membro_params
      params.require(:membro).permit(:paroquia_id, :sexo, :nome, :apelido, :data_nascimento, :profissao_id, :endereco_profissao, :telefone_profissao, :religiao, :casamento_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casamentos_helper.rb
module CasamentosHelper
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/helpers/filhos_helper.rb
module FilhosHelper
end

app/helpers/membros_helper.rb
module MembrosHelper
end

app/helpers/paroquia_helper.rb
module ParoquiaHelper
end

app/helpers/perfils_helper.rb
module PerfilsHelper
end

app/helpers/profissaos_helper.rb
module ProfissaosHelper
end

app/helpers/religiaos_helper.rb
module ReligiaosHelper
end

app/helpers/residencia_helper.rb
module ResidenciaHelper
end

app/views/casamentos/_form.html.slim
= form_for @casamento do |f|
  - if @casamento.errors.any?
    #error_explanation
      h2 = "#{pluralize(@casamento.errors.count, "error")} prohibited this casamento from being saved:"
      ul
        - @casamento.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :paroquia_id
    = f.number_field :paroquia_id
  .field
    = f.label :esposo
    = f.number_field :esposo
  .field
    = f.label :esposa
    = f.number_field :esposa
  .field
    = f.label :data
    = f.date_select :data
  .field
    = f.label :religioso
    = f.check_box :religioso
  .field
    = f.label :civil
    = f.check_box :civil
  .field
    = f.label :separados
    = f.check_box :separados
  .actions = f.submit

app/views/casamentos/edit.html.slim
h1 Editing casamento

== render 'form'

= link_to 'Show', @casamento
'|
= link_to 'Back', casamentos_path

app/views/casamentos/index.html.slim
h1 Listing casamentos

table
  thead
    tr
      th Paroquia
      th Esposo
      th Esposa
      th Data
      th Religioso
      th Civil
      th Separados
      th
      th
      th

  tbody
    - @casamentos.each do |casamento|
      tr
        td = casamento.paroquia_id
        td = casamento.esposo
        td = casamento.esposa
        td = casamento.data
        td = casamento.religioso
        td = casamento.civil
        td = casamento.separados
        td = link_to 'Show', casamento
        td = link_to 'Edit', edit_casamento_path(casamento)
        td = link_to 'Destroy', casamento, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Casamento', new_casamento_path

app/views/casamentos/new.html.slim
h1 New casamento

== render 'form'

= link_to 'Back', casamentos_path

app/views/casamentos/show.html.slim
p#notice = notice

p
  strong Paroquia:
  = @casamento.paroquia_id
p
  strong Esposo:
  = @casamento.esposo
p
  strong Esposa:
  = @casamento.esposa
p
  strong Data:
  = @casamento.data
p
  strong Religioso:
  = @casamento.religioso
p
  strong Civil:
  = @casamento.civil
p
  strong Separados:
  = @casamento.separados

= link_to 'Edit', edit_casamento_path(@casamento)
'|
= link_to 'Back', casamentos_path