config/routes.rb
Rails.application.routes.draw do

  
  
  resources :perfils
  resources :religiaos
  resources :enderecos
  resources :paroquias
  resources :filhos
  resources :profissaos
  resources :casamentos
  resources :membros
  devise_for :usuarios 
  root  to: 'casamentos#index'
  

end

app/models/casamento.rb
class Casamento < ActiveRecord::Base
end

app/models/endereco.rb
class Endereco < ActiveRecord::Base
end

app/models/filho.rb
class Filho < ActiveRecord::Base
    belongs_to :casamento
end

app/models/membro.rb
class Membro < ActiveRecord::Base
    belongs_to :profissao
    belongs_to :paroquia
    belongs_to :usuario
    belongs_to :casamento
    belongs_to :religiao
    belongs_to :endereco
    belongs_to :endereco_profissional, class_name: 'Endereco', foreign_key: :endereco_profissao_id    
end

app/models/paroquia.rb
class Paroquia < ActiveRecord::Base
    self.table_name = :paroquias
    belongs_to :endereco
end

app/models/perfil.rb
class Perfil < ActiveRecord::Base
end

app/models/profissao.rb
class Profissao < ActiveRecord::Base
end

app/models/religiao.rb
class Religiao < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :esposo, class_name: 'Membro', foreign_key: :usuario_id
  has_one :esposa, class_name: 'Membro', foreign_key: :usuario_id

  

  accepts_nested_attributes_for :esposo
  accepts_nested_attributes_for :esposa
  belongs_to :perfil
end

app/controllers/filhos_controller.rb
class FilhosController < GeccController
  before_action :set_filho, only: [:show, :edit, :update, :destroy]

  # GET /filhos
  # GET /filhos.json
  def index
    @filhos = Filho.all
  end

  # GET /filhos/1
  # GET /filhos/1.json
  def show
  end

  # GET /filhos/new
  def new
    @filho = Filho.new
  end

  # GET /filhos/1/edit
  def edit
  end

  # POST /filhos
  # POST /filhos.json
  def create
    @filho = Filho.new(filho_params)

    respond_to do |format|
      if @filho.save
        format.html { redirect_to @filho, notice: 'Filho was successfully created.' }
        format.json { render :show, status: :created, location: @filho }
      else
        format.html { render :new }
        format.json { render json: @filho.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /filhos/1
  # PATCH/PUT /filhos/1.json
  def update
    respond_to do |format|
      if @filho.update(filho_params)
        format.html { redirect_to @filho, notice: 'Filho was successfully updated.' }
        format.json { render :show, status: :ok, location: @filho }
      else
        format.html { render :edit }
        format.json { render json: @filho.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filhos/1
  # DELETE /filhos/1.json
  def destroy
    @filho.destroy
    respond_to do |format|
      format.html { redirect_to filhos_url, notice: 'Filho was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_filho
      @filho = Filho.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def filho_params
      params.require(:filho).permit(:casamento_id, :nome, :data_nascimento)
    end
end

app/controllers/gecc_controller.rb
class GeccController < ApplicationController
    before_action :authenticate_user!
end

app/controllers/membros_controller.rb
class MembrosController < GeccController
  before_action :set_membro, only: [:show, :edit, :update, :destroy]

  # GET /membros
  # GET /membros.json
  def index
    @membros = Membro.all
  end

  # GET /membros/1
  # GET /membros/1.json
  def show
  end

  # GET /membros/new
  def new
    @membro = Membro.new
  end

  # GET /membros/1/edit
  def edit
  end

  # POST /membros
  # POST /membros.json
  def create
    @membro = Membro.new(membro_params)

    respond_to do |format|
      if @membro.save
        format.html { redirect_to @membro, notice: 'Membro was successfully created.' }
        format.json { render :show, status: :created, location: @membro }
      else
        format.html { render :new }
        format.json { render json: @membro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /membros/1
  # PATCH/PUT /membros/1.json
  def update
    respond_to do |format|
      if @membro.update(membro_params)
        format.html { redirect_to @membro, notice: 'Membro was successfully updated.' }
        format.json { render :show, status: :ok, location: @membro }
      else
        format.html { render :edit }
        format.json { render json: @membro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /membros/1
  # DELETE /membros/1.json
  def destroy
    @membro.destroy
    respond_to do |format|
      format.html { redirect_to membros_url, notice: 'Membro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membro
      @membro = Membro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membro_params
      params.require(:membro).permit(:paroquia_id, :sexo, :nome, :apelido, :data_nascimento, :profissao_id, :endereco_profissao, :telefone_profissao, :religiao, :casamento_id)
    end
end

app/controllers/perfils_controller.rb
class PerfilsController < GeccController
  before_action :set_perfil, only: [:show, :edit, :update, :destroy]

  # GET /perfils
  # GET /perfils.json
  def index
    @perfils = Perfil.all
  end

  # GET /perfils/1
  # GET /perfils/1.json
  def show
  end

  # GET /perfils/new
  def new
    @perfil = Perfil.new
  end

  # GET /perfils/1/edit
  def edit
  end

  # POST /perfils
  # POST /perfils.json
  def create
    @perfil = Perfil.new(perfil_params)

    respond_to do |format|
      if @perfil.save
        format.html { redirect_to @perfil, notice: 'Perfil was successfully created.' }
        format.json { render :show, status: :created, location: @perfil }
      else
        format.html { render :new }
        format.json { render json: @perfil.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /perfils/1
  # PATCH/PUT /perfils/1.json
  def update
    respond_to do |format|
      if @perfil.update(perfil_params)
        format.html { redirect_to @perfil, notice: 'Perfil was successfully updated.' }
        format.json { render :show, status: :ok, location: @perfil }
      else
        format.html { render :edit }
        format.json { render json: @perfil.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /perfils/1
  # DELETE /perfils/1.json
  def destroy
    @perfil.destroy
    respond_to do |format|
      format.html { redirect_to perfils_url, notice: 'Perfil was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_perfil
      @perfil = Perfil.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def perfil_params
      params.require(:perfil).permit(:nome)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casamentos_helper.rb
module CasamentosHelper
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/helpers/filhos_helper.rb
module FilhosHelper
end

app/helpers/membros_helper.rb
module MembrosHelper
end

app/helpers/paroquia_helper.rb
module ParoquiaHelper
end

app/helpers/perfils_helper.rb
module PerfilsHelper
end

app/helpers/profissaos_helper.rb
module ProfissaosHelper
end

app/helpers/religiaos_helper.rb
module ReligiaosHelper
end

app/helpers/residencia_helper.rb
module ResidenciaHelper
end

app/views/filhos/_form.html.slim
= form_for @filho do |f|
  - if @filho.errors.any?
    #error_explanation
      h2 = "#{pluralize(@filho.errors.count, "error")} prohibited this filho from being saved:"
      ul
        - @filho.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :casamento_id
    = f.text_field :casamento_id
  .field
    = f.label :nome
    = f.text_field :nome
  .field
    = f.label :data_nascimento
    = f.date_select :data_nascimento
  .actions = f.submit

app/views/filhos/edit.html.slim
h1 Editing filho

== render 'form'

= link_to 'Show', @filho
'|
= link_to 'Back', filhos_path

app/views/filhos/index.html.slim
h1 Listing filhos

table
  thead
    tr
      th Casamento
      th Nome
      th Data nascimento
      th
      th
      th

  tbody
    - @filhos.each do |filho|
      tr
        td = filho.casamento_id
        td = filho.nome
        td = filho.data_nascimento
        td = link_to 'Show', filho
        td = link_to 'Edit', edit_filho_path(filho)
        td = link_to 'Destroy', filho, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Filho', new_filho_path

app/views/filhos/new.html.slim
h1 New filho

== render 'form'

= link_to 'Back', filhos_path

app/views/filhos/show.html.slim
p#notice = notice

p
  strong Casamento:
  = @filho.casamento_id
p
  strong Nome:
  = @filho.nome
p
  strong Data nascimento:
  = @filho.data_nascimento

= link_to 'Edit', edit_filho_path(@filho)
'|
= link_to 'Back', filhos_path

app/views/membros/_form.html.slim
= form_for @membro do |f|
  - if @membro.errors.any?
    #error_explanation
      h2 = "#{pluralize(@membro.errors.count, "error")} prohibited this membro from being saved:"
      ul
        - @membro.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :paroquia_id
    = f.number_field :paroquia_id
  .field
    = f.label :sexo
    = f.text_field :sexo
  .field
    = f.label :nome
    = f.text_field :nome
  .field
    = f.label :apelido
    = f.text_field :apelido
  .field
    = f.label :data_nascimento
    = f.date_select :data_nascimento
  .field
    = f.label :profissao_id
    = f.number_field :profissao_id
  .field
    = f.label :endereco_profissao
    = f.text_field :endereco_profissao
  .field
    = f.label :telefone_profissao
    = f.text_field :telefone_profissao
  .field
    = f.label :religiao
    = f.text_field :religiao
  .field
    = f.label :casamento_id
    = f.number_field :casamento_id
  .actions = f.submit

app/views/membros/edit.html.slim
h1 Editing membro

== render 'form'

= link_to 'Show', @membro
'|
= link_to 'Back', membros_path

app/views/membros/index.html.slim
h1 Listing membros

table
  thead
    tr
      th Paroquia
      th Sexo
      th Nome
      th Apelido
      th Data nascimento
      th Profissao
      th Endereco profissao
      th Telefone profissao
      th Religiao
      th Casamento
      th
      th
      th

  tbody
    - @membros.each do |membro|
      tr
        td = membro.paroquia_id
        td = membro.sexo
        td = membro.nome
        td = membro.apelido
        td = membro.data_nascimento
        td = membro.profissao_id
        td = membro.endereco_profissao
        td = membro.telefone_profissao
        td = membro.religiao
        td = membro.casamento_id
        td = link_to 'Show', membro
        td = link_to 'Edit', edit_membro_path(membro)
        td = link_to 'Destroy', membro, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Membro', new_membro_path

app/views/membros/new.html.slim
h1 New membro

== render 'form'

= link_to 'Back', membros_path

app/views/membros/show.html.slim
p#notice = notice

p
  strong Paroquia:
  = @membro.paroquia_id
p
  strong Sexo:
  = @membro.sexo
p
  strong Nome:
  = @membro.nome
p
  strong Apelido:
  = @membro.apelido
p
  strong Data nascimento:
  = @membro.data_nascimento
p
  strong Profissao:
  = @membro.profissao_id
p
  strong Endereco profissao:
  = @membro.endereco_profissao
p
  strong Telefone profissao:
  = @membro.telefone_profissao
p
  strong Religiao:
  = @membro.religiao
p
  strong Casamento:
  = @membro.casamento_id

= link_to 'Edit', edit_membro_path(@membro)
'|
= link_to 'Back', membros_path

app/views/perfils/_form.html.slim
= form_for @perfil do |f|
  - if @perfil.errors.any?
    #error_explanation
      h2 = "#{pluralize(@perfil.errors.count, "error")} prohibited this perfil from being saved:"
      ul
        - @perfil.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :nome
    = f.text_field :nome
  .actions = f.submit

app/views/perfils/edit.html.slim
h1 Editing perfil

== render 'form'

= link_to 'Show', @perfil
'|
= link_to 'Back', perfils_path

app/views/perfils/index.html.slim
h1 Listing perfils

table
  thead
    tr
      th Nome
      th
      th
      th

  tbody
    - @perfils.each do |perfil|
      tr
        td = perfil.nome
        td = link_to 'Show', perfil
        td = link_to 'Edit', edit_perfil_path(perfil)
        td = link_to 'Destroy', perfil, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Perfil', new_perfil_path

app/views/perfils/new.html.slim
h1 New perfil

== render 'form'

= link_to 'Back', perfils_path

app/views/perfils/show.html.slim
p#notice = notice

p
  strong Nome:
  = @perfil.nome

= link_to 'Edit', edit_perfil_path(@perfil)
'|
= link_to 'Back', perfils_path