config/routes.rb
Rails.application.routes.draw do

  
  
  resources :perfils
  resources :religiaos
  resources :enderecos
  resources :paroquias
  resources :filhos
  resources :profissaos
  resources :casamentos
  resources :membros
  devise_for :usuarios 
  root  to: 'casamentos#index'
  

end

app/models/casamento.rb
class Casamento < ActiveRecord::Base
end

app/models/endereco.rb
class Endereco < ActiveRecord::Base
end

app/models/filho.rb
class Filho < ActiveRecord::Base
    belongs_to :casamento
end

app/models/membro.rb
class Membro < ActiveRecord::Base
    belongs_to :profissao
    belongs_to :paroquia
    belongs_to :usuario
    belongs_to :casamento
    belongs_to :religiao
    belongs_to :endereco
    belongs_to :endereco_profissional, class_name: 'Endereco', foreign_key: :endereco_profissao_id    
end

app/models/paroquia.rb
class Paroquia < ActiveRecord::Base
    self.table_name = :paroquias
    belongs_to :endereco
end

app/models/perfil.rb
class Perfil < ActiveRecord::Base
end

app/models/profissao.rb
class Profissao < ActiveRecord::Base
end

app/models/religiao.rb
class Religiao < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :esposo, class_name: 'Membro', foreign_key: :usuario_id
  has_one :esposa, class_name: 'Membro', foreign_key: :usuario_id

  

  accepts_nested_attributes_for :esposo
  accepts_nested_attributes_for :esposa
  belongs_to :perfil
end

app/controllers/enderecos_controller.rb
class EnderecosController < GeccController
  before_action :set_endereco, only: [:show, :edit, :update, :destroy]

  # GET /enderecos
  # GET /enderecos.json
  def index
    @enderecos = Endereco.all
  end

  # GET /enderecos/1
  # GET /enderecos/1.json
  def show
  end

  # GET /enderecos/new
  def new
    @endereco = Endereco.new
  end

  # GET /enderecos/1/edit
  def edit
  end

  # POST /enderecos
  # POST /enderecos.json
  def create
    @endereco = Endereco.new(endereco_params)

    respond_to do |format|
      if @endereco.save
        format.html { redirect_to @endereco, notice: 'Endereco was successfully created.' }
        format.json { render :show, status: :created, location: @endereco }
      else
        format.html { render :new }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enderecos/1
  # PATCH/PUT /enderecos/1.json
  def update
    respond_to do |format|
      if @endereco.update(endereco_params)
        format.html { redirect_to @endereco, notice: 'Endereco was successfully updated.' }
        format.json { render :show, status: :ok, location: @endereco }
      else
        format.html { render :edit }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enderecos/1
  # DELETE /enderecos/1.json
  def destroy
    @endereco.destroy
    respond_to do |format|
      format.html { redirect_to enderecos_url, notice: 'Endereco was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_endereco
      @endereco = Endereco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def endereco_params
      params.require(:endereco).permit(:endereco, :numero, :complemento, :bairro, :cidade, :uf, :telefone)
    end
end

app/controllers/filhos_controller.rb
class FilhosController < GeccController
  before_action :set_filho, only: [:show, :edit, :update, :destroy]

  # GET /filhos
  # GET /filhos.json
  def index
    @filhos = Filho.all
  end

  # GET /filhos/1
  # GET /filhos/1.json
  def show
  end

  # GET /filhos/new
  def new
    @filho = Filho.new
  end

  # GET /filhos/1/edit
  def edit
  end

  # POST /filhos
  # POST /filhos.json
  def create
    @filho = Filho.new(filho_params)

    respond_to do |format|
      if @filho.save
        format.html { redirect_to @filho, notice: 'Filho was successfully created.' }
        format.json { render :show, status: :created, location: @filho }
      else
        format.html { render :new }
        format.json { render json: @filho.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /filhos/1
  # PATCH/PUT /filhos/1.json
  def update
    respond_to do |format|
      if @filho.update(filho_params)
        format.html { redirect_to @filho, notice: 'Filho was successfully updated.' }
        format.json { render :show, status: :ok, location: @filho }
      else
        format.html { render :edit }
        format.json { render json: @filho.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filhos/1
  # DELETE /filhos/1.json
  def destroy
    @filho.destroy
    respond_to do |format|
      format.html { redirect_to filhos_url, notice: 'Filho was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_filho
      @filho = Filho.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def filho_params
      params.require(:filho).permit(:casamento_id, :nome, :data_nascimento)
    end
end

app/controllers/gecc_controller.rb
class GeccController < ApplicationController
    before_action :authenticate_user!
end

app/controllers/membros_controller.rb
class MembrosController < GeccController
  before_action :set_membro, only: [:show, :edit, :update, :destroy]

  # GET /membros
  # GET /membros.json
  def index
    @membros = Membro.all
  end

  # GET /membros/1
  # GET /membros/1.json
  def show
  end

  # GET /membros/new
  def new
    @membro = Membro.new
  end

  # GET /membros/1/edit
  def edit
  end

  # POST /membros
  # POST /membros.json
  def create
    @membro = Membro.new(membro_params)

    respond_to do |format|
      if @membro.save
        format.html { redirect_to @membro, notice: 'Membro was successfully created.' }
        format.json { render :show, status: :created, location: @membro }
      else
        format.html { render :new }
        format.json { render json: @membro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /membros/1
  # PATCH/PUT /membros/1.json
  def update
    respond_to do |format|
      if @membro.update(membro_params)
        format.html { redirect_to @membro, notice: 'Membro was successfully updated.' }
        format.json { render :show, status: :ok, location: @membro }
      else
        format.html { render :edit }
        format.json { render json: @membro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /membros/1
  # DELETE /membros/1.json
  def destroy
    @membro.destroy
    respond_to do |format|
      format.html { redirect_to membros_url, notice: 'Membro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membro
      @membro = Membro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membro_params
      params.require(:membro).permit(:paroquia_id, :sexo, :nome, :apelido, :data_nascimento, :profissao_id, :endereco_profissao, :telefone_profissao, :religiao, :casamento_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casamentos_helper.rb
module CasamentosHelper
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/helpers/filhos_helper.rb
module FilhosHelper
end

app/helpers/membros_helper.rb
module MembrosHelper
end

app/helpers/paroquia_helper.rb
module ParoquiaHelper
end

app/helpers/perfils_helper.rb
module PerfilsHelper
end

app/helpers/profissaos_helper.rb
module ProfissaosHelper
end

app/helpers/religiaos_helper.rb
module ReligiaosHelper
end

app/helpers/residencia_helper.rb
module ResidenciaHelper
end

app/views/enderecos/_form.html.slim
= form_for @endereco do |f|
  - if @endereco.errors.any?
    #error_explanation
      h2 = "#{pluralize(@endereco.errors.count, "error")} prohibited this endereco from being saved:"
      ul
        - @endereco.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :endereco
    = f.text_field :endereco
  .field
    = f.label :numero
    = f.number_field :numero
  .field
    = f.label :complemento
    = f.text_field :complemento
  .field
    = f.label :bairro
    = f.text_field :bairro
  .field
    = f.label :cidade
    = f.text_field :cidade
  .field
    = f.label :uf
    = f.text_field :uf
  .field
    = f.label :telefone
    = f.text_field :telefone
  .actions = f.submit

app/views/enderecos/edit.html.slim
h1 Editing endereco

== render 'form'

= link_to 'Show', @endereco
'|
= link_to 'Back', enderecos_path

app/views/enderecos/index.html.slim
h1 Listing enderecos

table
  thead
    tr
      th Endereco
      th Numero
      th Complemento
      th Bairro
      th Cidade
      th Uf
      th Telefone
      th
      th
      th

  tbody
    - @enderecos.each do |endereco|
      tr
        td = endereco.endereco
        td = endereco.numero
        td = endereco.complemento
        td = endereco.bairro
        td = endereco.cidade
        td = endereco.uf
        td = endereco.telefone
        td = link_to 'Show', endereco
        td = link_to 'Edit', edit_endereco_path(endereco)
        td = link_to 'Destroy', endereco, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Endereco', new_endereco_path

app/views/enderecos/new.html.slim
h1 New endereco

== render 'form'

= link_to 'Back', enderecos_path

app/views/enderecos/show.html.slim
p#notice = notice

p
  strong Endereco:
  = @endereco.endereco
p
  strong Numero:
  = @endereco.numero
p
  strong Complemento:
  = @endereco.complemento
p
  strong Bairro:
  = @endereco.bairro
p
  strong Cidade:
  = @endereco.cidade
p
  strong Uf:
  = @endereco.uf
p
  strong Telefone:
  = @endereco.telefone

= link_to 'Edit', edit_endereco_path(@endereco)
'|
= link_to 'Back', enderecos_path